lab02/encuesta/urls.py
from django.urls import path

from . import views

app_name = 'encuesta'

urlpatterns = [
    #ex: /encuesta/
    path('', views.index, name="index"),
    path('enviar', views.enviar, name='enviar'),
]

lab02/lab02/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('encuesta/', include('encuesta.urls')),
    path('admin/', admin.site.urls),
]

lab02/encuesta/models.py
from django.db import models

# Create your models here.

lab02/encuesta/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context = {
        'titulo' : "Formulario",
    }
    return render(request, 'encuesta/formulario.html', context)

def enviar(request):
    context = {
        'titulo': 'Respuesta',
        'diametro':request.POST['diametro'],
        'altura': request.POST['altura'],
        'resultado':float(3.141592)*float(request.POST['altura'])*float(request.POST['diametro'])*float(request.POST['diametro']),
    }
    return render(request, 'encuesta/respuesta.html', context)

lab02/encuesta/templates/encuesta/formulario.html
<h2>{{titulo}}</h2>
<h1>CÁLCULO DEL VOLUMEN DEL CILINDRO</h1>
<form action="{% url 'encuesta:enviar' %}" method="post">
    {% csrf_token %}
    Introduzca el diametro en metros
    <input type="number" name="diametro" step="any"><br>
    Introduzca la altura en metros
    <input type="number" name="altura" step="any"><br>
    <input type="submit" name="submit" value="Enviar">
</form>

lab02/encuesta/templates/encuesta/respuesta.html
<h2>{{ titulo }} </h2>

<p>El volumen del cilindro es de {{ resultado }} metros cubicos</p>

lab02/encuesta/templates/multi/operacion.html
<h1>CÁLCULO DEL VOLUMEN DEL CILINDRO</h1>
<form action="{% url 'encuesta:enviar' %}" method="post">
    {% csrf_token %}
    Introduzca el diametro en metros
    <input type="number" name="diametro"><br>
    Introduzca la altura en metros
    <input type="number" name="altura"><br>
    <input type="submit" name="submit" value="Enviar">
</form>