lab06/lab06/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('tienda/', include('tienda.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

lab06/tienda/urls.py
from django.urls import path

from . import views

app_name= 'tienda'

urlpatterns = [
    path('', views.index, name='index'),
    path('producto/<int:producto_id>', views.producto, name='producto'),
    path('agregarCarrito/<int:producto_id>',views.agregarCarrito,name='agregarCarrito'),
    path('carrito',views.carrito,name='carrito'),
    path('eliminarProductoCarrito/<int:producto_id>',views.eliminarProductoCarrito,name="eliminarProductoCarrito"),
    path('limpiarCarrito',views.limpiarCarrito,name='limpiarCarrito')

]

lab06/tienda/models.py
from django.db import models


class Categoria(models.Model):
    nombre = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.nombre
    
class Producto(models.Model):
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=200)
    precio = models.DecimalField(max_digits=6, decimal_places=2)
    stock = models.IntegerField(default=0)
    imagen = models.ImageField(upload_to='productos',blank=True,null=True)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.nombre
    
    
# Create your models here.

lab06/tienda/views.py
from django.shortcuts import get_object_or_404, render

from .models import Categoria,Producto

from tienda.carrito import Cart
# Create your views here.

def index(request):
    product_list = Producto.objects.order_by('nombre')[:6]
    context = {'product_list':product_list}
    return render(request, 'index.html', context)

def producto(request,producto_id):
    producto= get_object_or_404(Producto,pk=producto_id)
    return render(request, 'producto.html',{'producto':producto})

def agregarCarrito(request,producto_id):
    objProducto = Producto.objects.get(id=producto_id)
    carritoProducto = Cart(request)
    carritoProducto.add(objProducto,1)
    print(request.session.get("cart"))
    return render(request,'carrito.html')

def eliminarProductoCarrito(request,producto_id):
    objProducto = Producto.objects.get(id=producto_id)
    carritoProducto = Cart(request)
    carritoProducto.remove(objProducto)
    
    return render(request,'carrito.html')

def limpiarCarrito(request):
    CarritoProducto = Cart(request)
    CarritoProducto.clear()
    print(request.session.get("cart"))
    return render(request,'carrito.html')

def carrito(request):
    print(request.session.get("cart"))
    return render(request,'carrito.html')

lab06/tienda/templates/carrito.html
{% extends "layout.html" %}
{% block content %}
<div class="container px-3 my-5 clearfix">
    <!-- Shopping cart table -->
    <div class="card">
        <div class="card-header">
            <h2>Carrito de Compras</h2>
        </div>
        <div class="card-body">
            <div class="table-responsive">
              <table class="table table-bordered m-0">
                <thead>
                  <tr>
                    <!-- Set columns width -->
                    <th class="text-center py-3 px-4" style="min-width: 400px;">Producto</th>
                    <th class="text-right py-3 px-4" style="width: 100px;">Precio</th>
                    <th class="text-center py-3 px-4" style="width: 120px;">Cantidad</th>
                    <th class="text-right py-3 px-4" style="width: 100px;">Total</th>
                    <th class="text-center align-middle py-3 px-0" style="width: 40px;"><a href="#" class="shop-tooltip float-none text-light" title="" data-original-title="Clear cart"><i class="ino ion-md-trash"></i></a></th>
                  </tr>
                </thead>
                <tbody>
                {% for key,value in request.session.cart.items %}
                  <tr>
                    <td class="p-4">
                      <div class="media align-items-center">
                        <img src="{{ value.imagen }}" width="100px" class="d-block ui-w-40 ui-bordered mr-4" alt="">
                        <div class="media-body">
                          <a href="{% url 'tienda:producto' value.producto_id %}" class="d-block text-dark">{{ value.nombre }}</a>
                        </div>
                      </div>
                    </td>
                    <td class="text-right font-weight-semibold align-middle p-4">{{ value.precio }}</td>
                    <td class="align-middle p-4"><input type="text" class="form-control text-center" value="{{ value.cantidad }}"></td>
                    <td class="text-right font-weight-semibold align-middle p-4">{{ value.total }}</td>
                    <td class="text-center align-middle px-0"><a href="{% url 'tienda:eliminarProductoCarrito' value.producto_id %}" class="shop-tooltip close float-none text-danger" title="" data-original-title="Remove">×</a></td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
                
            <!-- / Shopping cart table -->     
            <div class="float-right">
              <a class="btn btn-primary" href="{% url 'tienda:index' %}" role="button">REGRESAR</a>
              <a class="btn btn-primary" href="{% url 'tienda:limpiarCarrito' %}" role="button">LIMPIAR</a>   
            </div>
          </div>
      </div>
  </div>
{% endblock %}

lab06/tienda/templates/index.html
{% extends "layout.html" %}
{% block content %}
<div id="carouselExampleIndicators">
</div>

<div class="row">
    {% for producto in product_list %}
    <div class="col-lg-4 col-md-6 mb-4">
        <div class="card h-100">
            <a href="#"><img class="card-img-top" src= "{{ producto.imagen.url }}" alt=""></a>
            <div class="card-body">
            <h4 class="card-title">
                <a  href="producto/{{ producto.id }}">{{  producto.nombre }}</a>
            </h4>
            <h5 href>S/.{{producto.precio}}</h5>
            <p class="card-text">{{producto.categoria.nombre}}</p>
        </div>
        <div class="card-footer">
        <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
    </div>        
</div>
</div>
{% endfor %}
</div>
{% endblock %} 

lab06/tienda/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Shop Homepage</title>
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/shop.css' %}" rel="stylesheet">
  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">Lab 06</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Services</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">

      <div class="row">

        <div class="col-lg-3">
          <h1 class="my-4">Tiendita</h1>
          <div class="list-group">
            <a href="#" class="list-group-item">Categoria 1</a>
            <a href="#" class="list-group-item">Categoria 2</a>
            <a href="#" class="list-group-item">Categoria 3</a>
          </div>
        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">

          <!-- Block Content -->
          {% block content %}{% endblock %}
          <!-- /Block Content -->
          
        </div>
        <!-- /.col-lg-9 -->

      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  </body>

</html>

lab06/tienda/templates/producto.html
{% extends "layout.html" %}
{% block content %}
<br/>
<div class="col-lg-9">

    <div class="card mt-4">
      <img class="card-img-top img-fluid" src="
      {%if producto.imagen != null %}
      {{ producto.imagen.url }}
      {% endif %}" alt="">
      <div class="card-body">
        <h3 class="card-title">{{producto.nombre}}</h3>
        <h4>S/.{{producto.precio}}</h4>
        <p class="card-text">{{producto.categoria.nombre}}</p>
        <span class="text-warning">&#9733; &#9733; &#9733; &#9733; &#9734;</span>
        4.0 stars
        <a class="btn btn-primary" href="{% url 'tienda:agregarCarrito' producto.id %}" role="button">Agregar al carrito</a>
      </div>
    </div>
    <!-- /.card -->

    <div class="card card-outline-secondary my-4">
      <div class="card-header">
        Product Reviews
      </div>
      <div class="card-body">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.</p>
        <small class="text-muted">Posted by Anonymous on 3/1/17</small>
        <hr>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.</p>
        <small class="text-muted">Posted by Anonymous on 3/1/17</small>
        <hr>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.</p>
        <small class="text-muted">Posted by Anonymous on 3/1/17</small>
        <hr>
        <a href="#" class="btn btn-success">Leave a Review</a>
      </div>
    </div>
    <!-- /.card -->

</div>
{% endblock %}